version: '3.8'

services:
  vertica-ce:
    image: vertica/vertica-ce:latest
    container_name: vertica-mcp-test
    environment:
      VERTICA_DB_NAME: testdb
      VERTICA_DB_USER: testuser
      VERTICA_DB_PASSWORD: TestUser123!
    ports:
      - "5433:5433"
    volumes:
      - vertica_data:/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/opt/vertica/bin/vsql", "-U", "testuser", "-d", "testdb", "-c", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  vertica_data: